using System;
using System.Collections.Generic;

namespace PonyuDev.SherpaOnnx.Common.Platform
{
    /// <summary>
    /// Lists every file under StreamingAssets/SherpaOnnx/.
    /// Generated by the editor before build, consumed at runtime
    /// to copy files from APK to persistentDataPath on Android.
    /// </summary>
    /// <remarks>
    /// File set is split into <see cref="shared"/> (settings JSONs and
    /// other content not under a per-profile subfolder) and
    /// <see cref="profileGroups"/> (one entry per
    /// <c>{type}-models/{profileName}/</c> directory). Shared files are
    /// always extracted on first launch; profile groups extract lazily
    /// per active profile so individual profiles can be deleted to
    /// reclaim disk space without breaking other profiles.
    /// <para/>
    /// <see cref="files"/> is kept for backward compatibility with
    /// manifests generated by older builders — when
    /// <see cref="profileGroups"/> is empty,
    /// <see cref="StreamingAssetsCopier"/> falls back to extracting
    /// everything in <see cref="files"/> at once.
    /// </remarks>
    [Serializable]
    public sealed class StreamingAssetsManifest
    {
        /// <summary>
        /// Fingerprint of the file set (e.g. "42_31457280").
        /// Used to skip re-extraction when already up-to-date.
        /// </summary>
        public string version;

        /// <summary>
        /// Total size of all listed files in bytes.
        /// Used for storage space checks before extraction.
        /// </summary>
        public long totalSizeBytes;

        /// <summary>
        /// Legacy flat list — every file under
        /// <c>StreamingAssets/SherpaOnnx/</c>. Populated only when the
        /// manifest is built by an older builder; new builders leave
        /// this empty and use <see cref="shared"/> + <see cref="profileGroups"/>.
        /// </summary>
        public List<string> files = new();

        /// <summary>
        /// Files that do not belong to a per-profile subfolder
        /// (e.g. <c>SherpaOnnx/tts-settings.json</c>,
        /// <c>SherpaOnnx/microphone-settings.json</c>). Always extracted
        /// once at startup.
        /// </summary>
        public List<string> shared = new();

        /// <summary>
        /// Per-profile file groups, one entry per
        /// <c>{type}-models/{profileName}/</c> directory. Each group
        /// is extracted lazily when the active profile first needs it,
        /// and can be deleted independently.
        /// </summary>
        public List<StreamingAssetsManifestProfileGroup> profileGroups = new();
    }

    /// <summary>
    /// One entry of <see cref="StreamingAssetsManifest.profileGroups"/>.
    /// </summary>
    [Serializable]
    public sealed class StreamingAssetsManifestProfileGroup
    {
        /// <summary>
        /// Subdir under <c>SherpaOnnx/</c> the group lives in,
        /// e.g. <c>tts-models/vits-piper-en</c>. Forward slashes,
        /// no leading or trailing slash.
        /// </summary>
        public string subdir;

        /// <summary>
        /// Total size of the group's files in bytes — used for the
        /// disk-space check before per-profile extraction.
        /// </summary>
        public long sizeBytes;

        /// <summary>
        /// Relative paths of the group's files from StreamingAssets
        /// root (e.g. <c>SherpaOnnx/tts-models/vits-piper-en/model.onnx</c>).
        /// </summary>
        public List<string> files = new();
    }
}
